### ISSUE TITLE
Set seed for reproducibility

### ISSUE THREAD

**Issue by LazDaria** [stuchly/Rphenoannoy#1]
Hi,

thanks for the great work!
Does the function recognize a set seed? 

Thanks in advance!

**Comment by stuchly** [comment]
I think it should. It uses Rcpp for the C++ code integration and the seed should be preserved seamlessly. 
I made some quick tests and it seems to be reproducible.

**Comment by LazDaria** [comment]
Perfect, thank you so much for the prompt reply!
